#!/bin/sh

BASEDIR=$(dirname $0)
cd $BASEDIR
cd ../
BASEDIR=$PWD

WINE_APP_PREFIX_PATH="${BASEDIR}/SharedSupport/prefix"
WINE_APP_BIN_PATH="${BASEDIR}/SharedSupport/wine/bin"
EXE_PATH="${BASEDIR}/SharedSupport/prefix"

PATH="${WINE_APP_BIN_PATH}":$PATH WINEPREFIX="${WINE_APP_PREFIX_PATH}" exec wine32on64 "$EXE_PATH" $EXE_FLAGS;
