MOLTENVK_LIB=$WINE_LIBS_PATH/libMoltenVK.dylib
cp $MOLTENVK_LIB $WINE_APP_ENGINE_PATH/lib/wine/x86_64-unix;
PATH="$WINE_APP_BIN_PATH":$PATH WINEPREFIX=$WINE_APP_PREFIX_PATH WINE=$WINE_APP_BIN_PATH/wine32on64 winetricks --force --unattended dxvk_macos.verb;