import { CssProps, SpacingProps } from '@interfaces';
import { Component } from 'solid-js';

export const withSpacing = <T,>(BaseComponent: Component<T>) => {
  return (props: T & SpacingProps & CssProps) => (
    <BaseComponent
      {...props}
      classList={{
        ...props.classList,
        'm-0': props.m == 0 || props.margin == 0,
        'm-1': props.m == 1 || props.margin == 1,
        'm-2': props.m == 2 || props.margin == 2,
        'm-3': props.m == 3 || props.margin == 3,
        'm-4': props.m == 4 || props.margin == 4,
        'm-5': props.m == 5 || props.margin == 5,
        'mt-0': props.mt == 0 || props.marginTop == 0,
        'mt-1': props.mt == 1 || props.marginTop == 1,
        'mt-2': props.mt == 2 || props.marginTop == 2,
        'mt-3': props.mt == 3 || props.marginTop == 3,
        'mt-4': props.mt == 4 || props.marginTop == 4,
        'mt-5': props.mt == 5 || props.marginTop == 5,
        'me-0': props.mr == 0 || props.marginRight == 0,
        'me-1': props.mr == 1 || props.marginRight == 1,
        'me-2': props.mr == 2 || props.marginRight == 2,
        'me-3': props.mr == 3 || props.marginRight == 3,
        'me-4': props.mr == 4 || props.marginRight == 4,
        'me-5': props.mr == 4 || props.marginRight == 5,
        'mb-0': props.mb == 0 || props.marginBottom == 0,
        'mb-1': props.mb == 1 || props.marginBottom == 1,
        'mb-2': props.mb == 2 || props.marginBottom == 2,
        'mb-3': props.mb == 3 || props.marginBottom == 3,
        'mb-4': props.mb == 4 || props.marginBottom == 4,
        'mb-5': props.mb == 5 || props.marginBottom == 5,
        'ms-0': props.ml == 0 || props.marginLeft == 0,
        'ms-1': props.ml == 1 || props.marginLeft == 1,
        'ms-2': props.ml == 2 || props.marginLeft == 2,
        'ms-3': props.ml == 3 || props.marginLeft == 3,
        'ms-4': props.ml == 4 || props.marginLeft == 4,
        'ms-5': props.ml == 4 || props.marginLeft == 5,
        'mx-0': props.mx == 0 || props.marginX == 0,
        'mx-1': props.mx == 1 || props.marginX == 1,
        'mx-2': props.mx == 2 || props.marginX == 2,
        'mx-3': props.mx == 3 || props.marginX == 3,
        'mx-4': props.mx == 4 || props.marginX == 4,
        'mx-5': props.mx == 4 || props.marginX == 5,
        'my-0': props.my == 0 || props.marginY == 0,
        'my-1': props.my == 1 || props.marginY == 1,
        'my-2': props.my == 2 || props.marginY == 2,
        'my-3': props.my == 3 || props.marginY == 3,
        'my-4': props.my == 4 || props.marginY == 4,
        'my-5': props.my == 4 || props.marginY == 5,
        'p-0': props.p == 0 || props.padding == 0,
        'p-1': props.p == 1 || props.padding == 1,
        'p-2': props.p == 2 || props.padding == 2,
        'p-3': props.p == 3 || props.padding == 3,
        'p-4': props.p == 4 || props.padding == 4,
        'p-5': props.p == 5 || props.padding == 5,
        'pt-0': props.pt == 0 || props.paddingTop == 0,
        'pt-1': props.pt == 1 || props.paddingTop == 1,
        'pt-2': props.pt == 2 || props.paddingTop == 2,
        'pt-3': props.pt == 3 || props.paddingTop == 3,
        'pt-4': props.pt == 4 || props.paddingTop == 4,
        'pt-5': props.pt == 5 || props.paddingTop == 5,
        'pe-0': props.pr == 0 || props.paddingRight == 0,
        'pe-1': props.pr == 1 || props.paddingRight == 1,
        'pe-2': props.pr == 2 || props.paddingRight == 2,
        'pe-3': props.pr == 3 || props.paddingRight == 3,
        'pe-4': props.pr == 4 || props.paddingRight == 4,
        'pe-5': props.pr == 4 || props.paddingRight == 5,
        'pb-0': props.pb == 0 || props.paddingBottom == 0,
        'pb-1': props.pb == 1 || props.paddingBottom == 1,
        'pb-2': props.pb == 2 || props.paddingBottom == 2,
        'pb-3': props.pb == 3 || props.paddingBottom == 3,
        'pb-4': props.pb == 4 || props.paddingBottom == 4,
        'pb-5': props.pb == 5 || props.paddingBottom == 5,
        'ps-0': props.pl == 0 || props.paddingLeft == 0,
        'ps-1': props.pl == 1 || props.paddingLeft == 1,
        'ps-2': props.pl == 2 || props.paddingLeft == 2,
        'ps-3': props.pl == 3 || props.paddingLeft == 3,
        'ps-4': props.pl == 4 || props.paddingLeft == 4,
        'ps-5': props.pl == 4 || props.paddingLeft == 5,
        'px-0': props.px == 0 || props.paddingX == 0,
        'px-1': props.px == 1 || props.paddingX == 1,
        'px-2': props.px == 2 || props.paddingX == 2,
        'px-3': props.px == 3 || props.paddingX == 3,
        'px-4': props.px == 4 || props.paddingX == 4,
        'px-5': props.px == 5 || props.paddingX == 5,
        'py-0': props.py == 0 || props.paddingY == 0,
        'py-1': props.py == 1 || props.paddingY == 1,
        'py-2': props.py == 2 || props.paddingY == 2,
        'py-3': props.py == 3 || props.paddingY == 3,
        'py-4': props.py == 4 || props.paddingY == 4,
        'py-5': props.py == 5 || props.paddingY == 5,
        'm-auto': props.m === 'auto' || props.margin == 'auto',
        'mx-auto': props.m === 'auto' || props.margin == 'auto',
      }}
    />
  );
};
