export type BashScript =
  | 'buildAppPath'
  | 'bundleApp'
  | 'cmd'
  | 'scaffoldApp'
  | 'enableDxvk'
  | 'extractWineEngine'
  | 'listAppExecutables'
  | 'loadDylibs'
  | 'regedit'
  | 'runProgram'
  | 'taskmgr'
  | 'uninstaller'
  | 'wine'
  | 'wineboot'
  | 'winecfg'
  | 'winefile'
  | 'winetrick';
