export type BashScript =
  | 'tests/printHelloWorld'
  | 'tests/scriptWithError'
  | 'tests/beepDialog'
  | 'tests/pipe'
  | 'tests/sum'
  | 'buildAppPath'
  | 'bundleApp'
  | 'createWineAppFolder'
  | 'extractWineEngine'
  | 'generateWinePrefix'
  | 'runProgram'
  | 'winecfg'
  | 'winetrick'
  | 'enableDxvk'
  | 'listAppExecutables';
